### ISSUE TITLE
Actions fails with error: app.yaml does not exist

### ISSUE THREAD

**Issue by jr-cologne** [actions-hub/gcloud#1]
Hi @exelban,

I just discovered your Action and encountered the following error when trying it out for the first time:
```
ERROR: (gcloud.app.deploy) [/github/workspace/app.yaml] does not exist.
```

As you can see in my [workflow file](https://github.com/jr-cologne/CryptoStatus/blob/master/.github/workflows/deploy.yml), I'm using your Action in order to deploy my application to Google App Engine.
Here's the log of the job which failed: [click](https://github.com/jr-cologne/CryptoStatus/runs/200571909)

Unfortunately, I don't really have an idea what all the docker stuff means, but if I would need to guess, it might have something to do with the files from the repository not being synced to the docker container correctly.

Do you have any idea what the issue might be?
I'm wondering whether this is a bug in your Action or just me failing to use it correctly.

Thank you in advance and best regards,
@jr-cologne

**Comment by exelban** [comment]
@jr-cologne thanks, i will take a look for this today

**Comment by exelban** [comment]
@jr-cologne I'm guessing it because your project file is not available inside the container.
Try to add this step before gcloud:
```yarn
- uses: actions/checkout@v1
```

This action will copy your repo files to the container.

**Comment by exelban** [comment]
@jr-cologne try this one:
```yarn
  deploy:
    needs: set-env-vars
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: exelban/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml cron.yaml
```

**Comment by jr-cologne** [comment]
Hi @exelban,

thank you very much for this quick help.
It works now thanks to adding the checkout action!

I am going to close this issue.

Have a nice evening!

Best regards,
@jr-cologne
