### ISSUE TITLE
Deprecating set-env and add-path commands.

### ISSUE THREAD

**Issue by Mike-Dunton** [actions-hub/gcloud#19]
Warnings while using the action. 

```
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

The code at issue here is at the following lines  -> https://github.com/actions-hub/gcloud/blob/master/entrypoint.sh#L59-L60

According to this blog post  https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> Action and workflow authors who are setting environment variables via stdout should update any usage of the set-env and add-path workflow commands to use the new environment files.

Documentation on adding to the system path. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path

```
echo "{path}" >> $GITHUB_PATH
```

**Comment by exelban** [comment]
Thanks for your contribution.
