### ISSUE TITLE
Question about PROJECT_ID parameter

### ISSUE THREAD

**Issue by HaveF** [actions-hub/gcloud#22]
Thanks for this repo!

About
> PROJECT_ID - must be provided to activate a specific project.

Do we really need this? In service account(json), it already has project_id in it?

**Comment by exelban** [comment]
Hi.

I remember that there was some problem with this. But now I'm not sure why I decided to make it as env.
In theory, it could be changed. I don't when I will have free time to add this option.

But I always glad for PR)

**Comment by HaveF** [comment]
A quick view about the logic.

It seems related with `PREVIOUS_PROJECT_ID` thing, OK, let it be.

Thanks
