### ISSUE TITLE
Broken action using gcloud@master

### ISSUE THREAD

**Issue by jawnsy** [actions-hub/gcloud#26]
Dear maintainer,

You might already be aware of this, but I'm reporting it just in case. We use gcloud@master in our GitHub Actions, and the latest release seems to have broken some of our builds :sweat_smile: 

The cause seems to be that `google/cloud-sdk` does not have a tag `help-alpine` (at least, not visible in the [tag list on Docker Hub](https://hub.docker.com/r/google/cloud-sdk/tags?page=1&ordering=last_updated)), which seems to be making your own CI fail as well:

```console
  Dockerfile for action: '/home/runner/work/gcloud/gcloud/./Dockerfile'.
  /usr/bin/docker build -t 5588e4:65f5068b272d5bc3bbd5d4621223c059 -f "/home/runner/work/gcloud/gcloud/./Dockerfile" "/home/runner/work/gcloud/gcloud"
  manifest for google/cloud-sdk:help-alpine not found: manifest unknown: manifest unknown
  Sending build context to Docker daemon  95.23kB
  
  Step 1/6 : FROM google/cloud-sdk:help-alpine
```

The above is from your latest Actions build in master: https://github.com/actions-hub/gcloud/actions/runs/637630888

We are seeing a failure that looks very similar, and it happens prior to our build actually starting:

![image](https://user-images.githubusercontent.com/52710/110561223-28d39180-80fc-11eb-94b1-eba2b9e5fc0e.png)

**Comment by cranst0n** [comment]
Can confirm. Also seeing this error.

**Comment by msolovyov** [comment]
Found a workaround which is to just use the previous release:
` uses: actions-hub/gcloud@330.0.0`

**Comment by exelban** [comment]
Hi, Thanks for reporting. I have fixed the bug.
