### ISSUE TITLE
Error: 'ghcr.io/actions-hub/actions-hub-gcloud:343.0.0' should be either '[path]/Dockerfile' or 'docker://image[:tag]'

### ISSUE THREAD

**Issue by johnmalatras** [actions-hub/gcloud#31]
Getting this error on jobs beginning today. I ran some jobs yesterday so it's interesting that this wasn't picked up then- not sure if it's on GitHub's end or not. 

Here's the full logs from the "Set up Job" task:
```
Current runner version: '2.278.0'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@master'
Download action repository 'actions-hub/gcloud@master'
Error: 'ghcr.io/actions-hub/actions-hub-gcloud:343.0.0' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
```

**Comment by exelban** [comment]
Hi. #30 cause this error. Fixing...

**Comment by exelban** [comment]
ok. It must work now.

**Comment by justinwagg** [comment]
> ok. It must work now.

Working for me now, thanks @exelban :)

**Comment by johnmalatras** [comment]
Same here, thanks for the quick response!

**Comment by exelban** [comment]
Sorry for this. Don't notice that line in `action.yml` was changed. My bad(
