### ISSUE TITLE
Manifest unknown

### ISSUE THREAD

**Issue by peternoordijk** [actions-hub/gcloud#7]
The newest version of this action seems to fail after commit c93f62d7dd25f40e6d1ff284a4fdb684f8aee176 . 

```
manifest for google/cloud-sdk:285.0.0-alpine not found: manifest unknown: manifest unknown
```

![image](https://user-images.githubusercontent.com/5390610/76956493-72880280-6914-11ea-8bc0-920c7f8c412c.png)

**Comment by exelban** [comment]
@peternoordijk thanks. Looks like google does not upload a new version of sdk to docker hub.
I make a rollback to the previous stable version.

**Comment by peternoordijk** [comment]
@exelban that's strange... Anyway thanks for making the rollback

**Comment by exelban** [comment]
I thinks i must check if a new version exist in the docker hub. Or pulling sdk from google registry.

**Comment by peternoordijk** [comment]
Okay. Honestly I didn't dive into what's going on under the hood, but let me know if you need any help. This github action is really useful.

**Comment by exelban** [comment]
Thanks
