### ISSUE TITLE
gsutil for windows containers

### ISSUE THREAD

**Issue by 0xvishal** [actions-hub/gcloud#9]
I am getting an error if using windows containers in place of ubuntu.
So please assist me in how can I use gsutil for windows containers.

**Comment by exelban** [comment]
@0xvishal can you share the error?

**Comment by 0xvishal** [comment]
![Screenshot from 2020-03-20 17-52-45](https://user-images.githubusercontent.com/13795288/77163243-acebce00-6ad3-11ea-9447-64fa74a8ee70.png)

**Comment by 0xvishal** [comment]
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm install
    #- run: npm run make
    #- run: ls out/make/squirrel.windows/x64
    - run: ls
    
    - name: Deploy to Bucket
      uses: actions-hub/gcloud@master
      env:
            PROJECT_ID: dcdn
            APPLICATION_CREDENTIALS: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
            CLI: gsutil
      with: 
           args: cp package.json gs://cacher

**Comment by exelban** [comment]
@0xvishal Docker Action is only supported on Linux only. [https://help.github.com/en/actions/building-actions/about-actions#types-of-actions](https://help.github.com/en/actions/building-actions/about-actions#types-of-actions).

So it's not possible to use this action on non-linux OS.
